version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/golang:1.12"
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/marten-seemann/qpack
    steps:
      - checkout
      - run:
          name: "Setup build environment"
          command: |
            git submodule update --init --recursive
            go get github.com/onsi/ginkgo/ginkgo
            go get github.com/onsi/gomega
      - run:
          name: "Build infos"
          command: go version
      - run:
          name: "Run unit tests"
          command: ginkgo -race -cover -v -randomizeAllSpecs
      - run:
          name: "Run integration tests"
          command: ginkgo -r -race -v -randomizeAllSpecs -trace integrationtests
      - run:
          name: "Upload coverage report to Codecov"
          when: on_success
          command: |
            cat `find . -name "*.coverprofile"` > coverage.txt
            bash <(curl -s https://codecov.io/bash) -f coverage.txt
